// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTBeSTpwmc2Ak8YTYsv9NDp04AWBCoTr8',
    appId: '1:856068125924:web:55a84aace10799eb03e8f1',
    messagingSenderId: '856068125924',
    projectId: 'group415',
    authDomain: 'group415.firebaseapp.com',
    storageBucket: 'group415.firebasestorage.app',
    measurementId: 'G-KRGNVHLYVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLYcDvf6-b5c3s3CpgtKOGKCOZnsPSYS8',
    appId: '1:856068125924:android:2b73920b2f8609d003e8f1',
    messagingSenderId: '856068125924',
    projectId: 'group415',
    storageBucket: 'group415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRbzr2YyFbhxlRMDCJxremPEOOkTuyU9w',
    appId: '1:856068125924:ios:3be33bfe94b7dc4303e8f1',
    messagingSenderId: '856068125924',
    projectId: 'group415',
    storageBucket: 'group415.firebasestorage.app',
    iosBundleId: 'com.example.group415',
  );
}
